;this file for FamiTone4.2 library generated by text2vol4 tool
;edited by Doug Fraker, 2018, to add volume column, all notes, 
;and effects 1xx,2xx,4xx


song_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256 ; New song

.instruments:
	.db $70 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00
	.db $b0 ;instrument $02
	.dw .env3,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $ce,$cc,$cb,$c9,$c7,$c5,$c3,$c1,$c1,$c1,$00,$09
.env2:
	.db $cf,$c9,$c6,$c0,$00,$03
.env3:
	.db $c4,$c3,$05,$c4,$c4,$c0,$00,$05


; New song
.song0ch0:
	.db $fb,$05
.song0ch0loop:
.ref0:
	.db $8b,$80,$19,$85,$1b,$81,$1e,$81,$19,$87,$00,$83,$19,$85,$1d,$81
	.db $1e,$81,$22,$81
.ref1:
	.db $85,$00,$83,$23,$85,$25,$81,$27,$81,$25,$85,$20,$85,$20,$85,$1f
	.db $85,$1b,$81
.ref2:
	.db $8b,$1b,$85,$1d,$81,$1f,$81,$1e,$85,$1b,$85,$21,$85,$1e,$85,$1d
	.db $81
.ref3:
	.db $83,$14,$81,$19,$89,$1c,$85,$1b,$85,$12,$81,$17,$89,$1a,$85,$14
	.db $81
	.db $fd
	.dw .song0ch0loop

; New song
.song0ch1:
.song0ch1loop:
.ref4:
	.db $8b,$80,$22,$85,$23,$81,$25,$81,$1e,$87,$00,$83,$1e,$85,$20,$81
	.db $22,$81,$27,$81
.ref5:
	.db $85,$00,$83,$27,$85,$29,$81,$2a,$81,$29,$85,$25,$85,$22,$91
.ref6:
	.db $8b,$24,$85,$25,$81,$27,$81,$27,$85,$25,$85,$25,$85,$24,$85,$24
	.db $81
.ref7:
	.db $83,$1d,$81,$20,$89,$22,$85,$22,$85,$1b,$81,$1e,$89,$20,$85,$1d
	.db $81
	.db $fd
	.dw .song0ch1loop

; New song
.song0ch2:
.song0ch2loop:
.ref8:
	.db $84,$1e,$89,$19,$81,$19,$85,$1e,$85,$1b,$89,$16,$81,$16,$85,$1b
	.db $85
.ref9:
	.db $17,$89,$12,$81,$12,$85,$17,$85,$16,$85,$19,$81,$1a,$81,$1b,$81
	.db $1b,$81,$13,$81,$16,$81
.ref10:
	.db $18,$81,$18,$81,$00,$81,$13,$81,$22,$81,$13,$81,$18,$81,$21,$81
	.db $1d,$81,$2a,$85,$18,$81,$1d,$81,$27,$81,$15,$81,$25,$81
.ref11:
	.db $16,$89,$1b,$81,$1b,$81,$25,$81,$13,$81,$23,$81,$14,$89,$19,$81
	.db $19,$81,$23,$81,$1d,$81,$22,$81
	.db $fd
	.dw .song0ch2loop

; New song
.song0ch3:
.song0ch3loop:
.ref12:
	.db $82,$01,$00,$83,$0e,$00,$01,$00,$09,$85,$0e,$00,$01,$00,$01,$00
	.db $83,$0e,$00,$01,$00,$09,$85,$0e,$00,$01,$00
.ref13:
	.db $01,$00,$83,$0e,$00,$01,$00,$09,$85,$0e,$00,$01,$00,$01,$00,$83
	.db $0e,$00,$01,$00,$09,$85,$0e,$00,$01,$00
	.db $ff,$1a
	.dw .ref13
	.db $ff,$1a
	.dw .ref13
	.db $fd
	.dw .song0ch3loop

; New song
.song0ch4:
.song0ch4loop:
.ref16:
	.db $bf
.ref17:
	.db $bf
.ref18:
	.db $bf
.ref19:
	.db $bf
	.db $fd
	.dw .song0ch4loop
