;this file for FamiTone4.2 library generated by text2vol4 tool
;edited by Doug Fraker, 2018, to add volume column, all notes, 
;and effects 1xx,2xx,4xx


song_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256 ; New song

.instruments:
	.db $70 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $ce,$cc,$cb,$c9,$c7,$c5,$c3,$c1,$c1,$c1,$00,$09
.env2:
	.db $cf,$c9,$c6,$c0,$00,$03


; New song
.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $80,$20,$81,$00,$81,$20,$81,$00,$81,$21,$81,$20,$81
.ref1:
	.db $21,$81,$23,$85,$28,$81,$00,$81,$25,$81
.ref2:
	.db $83,$27,$81,$00,$81,$23,$81,$00,$81,$28,$81
.ref3:
	.db $00,$81,$2d,$85,$2c,$85,$25,$81
.ref4:
	.db $83,$27,$81,$28,$81,$28,$85,$27,$81
.ref5:
	.db $25,$81,$23,$81
	.db $fd
	.dw .song0ch0loop

; New song
.song0ch1:
.song0ch1loop:
.ref6:
	.db $80,$1b,$81,$00,$81,$1b,$81,$00,$81,$1c,$81,$00,$81
.ref7:
	.db $1b,$81,$1e,$85,$23,$81,$00,$81,$20,$81
.ref8:
	.db $17,$81,$1e,$81,$17,$81,$1e,$81,$17,$81,$20,$81
.ref9:
	.db $17,$81,$1e,$81,$17,$81,$1c,$81,$17,$81,$1e,$81
.ref10:
	.db $19,$81,$22,$81,$19,$81,$21,$81,$1b,$81,$1e,$81
.ref11:
	.db $1b,$81,$1e,$81
	.db $fd
	.dw .song0ch1loop

; New song
.song0ch2:
.song0ch2loop:
.ref12:
	.db $80,$1c,$81,$00,$81,$28,$00,$1c,$00,$1e,$81,$00,$81
.ref13:
	.db $2a,$00,$20,$81,$00,$81,$25,$00,$23,$00,$21,$00
.ref14:
	.db $21,$81,$00,$81,$21,$00,$20,$00,$20,$81,$00,$81
.ref15:
	.db $25,$00,$24,$00,$24,$81,$00,$81,$23,$00,$22,$00
.ref16:
	.db $22,$81,$00,$81,$22,$00,$21,$00,$21,$81,$00,$81
.ref17:
	.db $17,$00,$23,$00
	.db $fd
	.dw .song0ch2loop

; New song
.song0ch3:
.song0ch3loop:
.ref18:
	.db $82,$03,$81,$0f,$81,$09,$81,$0f,$81,$03,$81,$0f,$81
.ref19:
	.db $09,$81,$0f,$81,$03,$81,$0f,$81,$09,$81,$0f,$81
.ref20:
	.db $03,$81,$0f,$81,$09,$81,$0f,$81,$03,$81,$0f,$81
	.db $ff,$0c
	.dw .ref19
	.db $ff,$0c
	.dw .ref20
.ref23:
	.db $09,$81,$09,$09
	.db $fd
	.dw .song0ch3loop

; New song
.song0ch4:
.song0ch4loop:
.ref24:
	.db $97
.ref25:
	.db $97
.ref26:
	.db $97
.ref27:
	.db $97
.ref28:
	.db $97
.ref29:
	.db $87
	.db $fd
	.dw .song0ch4loop
