;this file for FamiTone4.2 library generated by text2vol4 tool
;edited by Doug Fraker, 2018, to add volume column, all notes, 
;and effects 1xx,2xx,4xx


song_music_data:
	.db 5
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256 ; New song
	.dw .song1ch0,.song1ch1,.song1ch2,.song1ch3,.song1ch4,307,256 ; New song
	.dw .song2ch0,.song2ch1,.song2ch2,.song2ch3,.song2ch4,307,256 ; New song
	.dw .song3ch0,.song3ch1,.song3ch2,.song3ch3,.song3ch4,307,256 ; New song
	.dw .song4ch0,.song4ch1,.song4ch2,.song4ch3,.song4ch4,307,256 ; New song

.instruments:
	.db $f0 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $30 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00
	.db $30 ;instrument $02
	.dw .env3,.env0,.env0
	.db $00
	.db $f0 ;instrument $03
	.dw .env4,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $ca,$c9,$c8,$c7,$c5,$c2,$c1,$02,$c1,$00,$08
.env2:
	.db $cb,$c7,$c4,$c2,$c0,$00,$04
.env3:
	.db $c4,$c3,$05,$c4,$c4,$c0,$00,$05
.env4:
	.db $ce,$cd,$cb,$c9,$c7,$c3,$c2,$c1,$c1,$c1,$00,$09


; New song
.song0ch0:
	.db $fb,$0a
.song0ch0loop:
.ref0:
	.db $85,$80,$19,$81,$1b,$1e,$19,$83,$00,$19,$81,$1d,$1e,$22
.ref1:
	.db $83,$00,$23,$81,$25,$27,$25,$81,$20,$81,$20,$81,$1f,$81,$1b
.ref2:
	.db $85,$1b,$81,$1d,$1f,$1e,$81,$1b,$81,$21,$81,$1e,$81,$1d
.ref3:
	.db $81,$14,$19,$83,$1c,$81,$1b,$81,$12,$17,$83,$1a,$81,$14
.ref4:
	.db $85,$19,$81,$1b,$1e,$19,$83,$00,$19,$81,$1d,$1e,$22
	.db $ff,$0f
	.dw .ref1
.ref6:
	.db $81,$18,$81,$1f,$81,$22,$24,$22,$81,$1d,$81,$1a,$81,$1d,$81,$1c
.ref7:
	.db $81,$1f,$81,$1e,$81,$21,$81,$20,$81,$23,$81,$22,$81,$25,$81,$1f
.ref8:
	.db $85,$1a,$81,$1e,$1f,$26,$81,$25,$81,$25,$81,$23,$81,$21
.ref9:
	.db $85,$18,$81,$1c,$1d,$24,$81,$23,$81,$23,$81,$21,$81,$1f
.ref10:
	.db $85,$17,$81,$1a,$1c,$23,$85,$1c,$81,$22,$81,$25
.ref11:
	.db $81,$21,$81,$20,$81,$17,$1c,$20,$1f,$16,$1b,$1f,$81,$21,$81,$1c
.ref12:
	.db $23,$81,$1c,$23,$81,$22,$81,$21,$81,$1a,$21,$81,$20,$83,$1c
	.db $ff,$0f
	.dw .ref12
.ref14:
	.db $23,$81,$1c,$23,$81,$22,$81,$21,$81,$1a,$21,$81,$20,$85
.ref15:
	.db $23,$81,$1c,$23,$81,$22,$81,$21,$81,$1a,$21,$81,$20,$83,$14
	.db $fd
	.dw .song0ch0loop

; New song
.song0ch1:
.song0ch1loop:
.ref16:
	.db $85,$80,$22,$81,$23,$25,$1e,$83,$00,$1e,$81,$20,$22,$27
.ref17:
	.db $83,$00,$27,$81,$29,$2a,$29,$81,$25,$81,$22,$87
.ref18:
	.db $85,$24,$81,$25,$27,$27,$81,$25,$81,$25,$81,$24,$81,$24
.ref19:
	.db $81,$1d,$20,$83,$22,$81,$22,$81,$1b,$1e,$83,$20,$81,$1d
.ref20:
	.db $85,$22,$81,$23,$25,$1e,$83,$00,$1e,$81,$20,$22,$27
	.db $ff,$0c
	.dw .ref17
.ref22:
	.db $85,$24,$81,$26,$27,$26,$81,$22,$81,$1d,$81,$22,$81,$1f
.ref23:
	.db $81,$24,$81,$21,$81,$26,$81,$23,$81,$28,$81,$25,$81,$2a,$81,$26
.ref24:
	.db $85,$2b,$81,$2d,$2f,$2f,$81,$2d,$81,$2d,$81,$2b,$81,$2a
.ref25:
	.db $85,$29,$81,$2b,$2d,$2d,$81,$2b,$81,$2b,$81,$29,$81,$28
.ref26:
	.db $85,$28,$81,$2a,$2b,$2a,$81,$28,$81,$24,$81,$25,$81,$28
.ref27:
	.db $81,$26,$95,$18,$81,$25
.ref28:
	.db $2a,$81,$20,$2a,$81,$2a,$81,$2a,$81,$25,$2a,$81,$2a,$83,$25
	.db $ff,$0f
	.dw .ref28
.ref30:
	.db $2a,$81,$20,$2a,$81,$2a,$81,$2a,$81,$25,$2a,$81,$2a,$1e,$20,$25
.ref31:
	.db $2a,$81,$20,$2a,$81,$2a,$81,$2a,$81,$25,$2a,$81,$2a,$81,$19,$1d
	.db $fd
	.dw .song0ch1loop

; New song
.song0ch2:
.song0ch2loop:
.ref32:
	.db $84,$1e,$83,$19,$19,$81,$1e,$81,$1b,$83,$16,$16,$81,$1b,$81
.ref33:
	.db $17,$83,$12,$12,$81,$17,$81,$16,$81,$19,$1a,$1b,$1b,$13,$16
.ref34:
	.db $18,$18,$81,$13,$22,$13,$18,$21,$1d,$2a,$81,$18,$1d,$27,$15,$25
.ref35:
	.db $16,$83,$1b,$1b,$25,$13,$23,$14,$83,$19,$19,$23,$1d,$22
.ref36:
	.db $1e,$83,$19,$19,$81,$1e,$81,$1b,$83,$16,$16,$81,$1b,$81
	.db $ff,$0f
	.dw .ref33
.ref38:
	.db $14,$14,$81,$1b,$1b,$81,$20,$81,$1f,$1f,$1a,$19,$18,$18,$24,$81
.ref39:
	.db $15,$81,$21,$15,$17,$81,$23,$17,$19,$81,$25,$19,$1b,$81,$27,$1b
.ref40:
	.db $1c,$1c,$81,$17,$17,$81,$1c,$81,$15,$83,$1c,$1c,$81,$21,$81
.ref41:
	.db $1a,$83,$15,$15,$81,$1a,$81,$1f,$83,$13,$13,$81,$1a,$81
.ref42:
	.db $18,$83,$1f,$1f,$81,$18,$81,$19,$83,$1e,$1e,$81,$12,$81
.ref43:
	.db $17,$83,$1c,$1c,$81,$10,$81,$18,$83,$1d,$1d,$81,$11,$81
.ref44:
	.db $12,$83,$19,$19,$81,$1e,$81,$10,$83,$17,$17,$81,$1c,$81
	.db $ff,$0e
	.dw .ref44
	.db $ff,$0e
	.dw .ref44
	.db $ff,$0e
	.dw .ref44
	.db $fd
	.dw .song0ch2loop

; New song
.song0ch3:
.song0ch3loop:
.ref48:
	.db $82,$01,$81,$0e,$01,$09,$81,$0e,$01,$01,$81,$0e,$01,$09,$81,$0e
	.db $01
.ref49:
	.db $01,$81,$0e,$01,$09,$81,$0e,$01,$01,$81,$0e,$01,$09,$81,$0e,$01
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
.ref55:
	.db $01,$81,$0e,$01,$09,$81,$0e,$01,$01,$81,$0e,$01,$09,$09,$01,$01
.ref56:
	.db $80,$02,$81,$82,$0e,$01,$09,$81,$0e,$01,$01,$81,$0e,$01,$09,$81
	.db $0e,$01
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref55
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
.ref63:
	.db $01,$81,$0e,$01,$09,$81,$0e,$01,$01,$81,$0e,$01,$09,$09,$01,$09
	.db $fd
	.dw .song0ch3loop

; New song
.song0ch4:
.song0ch4loop:
.ref64:
	.db $9f
.ref65:
	.db $9f
.ref66:
	.db $9f
.ref67:
	.db $9f
.ref68:
	.db $9f
.ref69:
	.db $9f
.ref70:
	.db $9f
.ref71:
	.db $9f
.ref72:
	.db $9f
.ref73:
	.db $9f
.ref74:
	.db $9f
.ref75:
	.db $9f
.ref76:
	.db $9f
.ref77:
	.db $9f
.ref78:
	.db $9f
.ref79:
	.db $9f
	.db $fd
	.dw .song0ch4loop


; New song
.song1ch0:
	.db $fb,$0c
.song1ch0loop:
.ref80:
	.db $85,$86,$20,$81,$21,$81,$24
.ref81:
	.db $81,$18,$81,$1d,$81,$21,$81,$1a
.ref82:
	.db $85,$1c,$81,$1f,$81,$24
.ref83:
	.db $81,$23,$81,$22,$81,$16,$81,$1f
.ref84:
	.db $85,$1f,$81,$1d,$81,$24
.ref85:
	.db $81,$1a,$81,$1d,$81,$20,$81,$20
	.db $fd
	.dw .song1ch0loop

; New song
.song1ch1:
.song1ch1loop:
.ref86:
	.db $85,$86,$17,$81,$19,$81,$1f
.ref87:
	.db $81,$1d,$81,$21,$81,$24,$81,$1f
.ref88:
	.db $85,$23,$81,$1c,$81,$28
.ref89:
	.db $81,$27,$81,$26,$81,$1c,$81,$24
.ref90:
	.db $85,$23,$81,$21,$81,$28
.ref91:
	.db $81,$1f,$81,$20,$81,$24,$81,$23
	.db $fd
	.dw .song1ch1loop

; New song
.song1ch2:
.song1ch2loop:
.ref92:
	.db $84,$15,$1c,$21,$31,$81,$32,$17,$34
.ref93:
	.db $1d,$2d,$1a,$30,$1f,$32,$13,$2f
.ref94:
	.db $18,$1f,$24,$37,$15,$30,$1a,$39
.ref95:
	.db $1f,$3b,$18,$37,$0c,$30,$18,$34
.ref96:
	.db $11,$18,$1d,$32,$1c,$30,$1a,$37
.ref97:
	.db $1f,$30,$13,$30,$1f,$32,$14,$34
	.db $fd
	.dw .song1ch2loop

; New song
.song1ch3:
.song1ch3loop:
.ref98:
	.db $82,$01,$81,$0c,$0f,$08,$81,$0c,$0f
.ref99:
	.db $01,$81,$0c,$0f,$08,$81,$0c,$0f
	.db $ff,$08
	.dw .ref99
	.db $ff,$08
	.dw .ref99
	.db $ff,$08
	.dw .ref99
.ref103:
	.db $01,$81,$0c,$0f,$08,$08,$01,$81
	.db $fd
	.dw .song1ch3loop

; New song
.song1ch4:
.song1ch4loop:
.ref104:
	.db $8f
.ref105:
	.db $8f
.ref106:
	.db $8f
.ref107:
	.db $8f
.ref108:
	.db $8f
.ref109:
	.db $8f
	.db $fd
	.dw .song1ch4loop


; New song
.song2ch0:
	.db $fb,$0c
.song2ch0loop:
.ref110:
	.db $81,$86,$0d,$81,$1d,$81,$14,$81,$0d,$81,$0f,$81,$1f,$81,$16,$81
	.db $0f,$81,$0c,$81,$1f,$81,$16,$81,$0c
	.db $fd
	.dw .song2ch0loop

; New song
.song2ch1:
.song2ch1loop:
.ref111:
	.db $86,$06,$81,$14,$81,$1b,$81,$16,$81,$08,$81,$16,$81,$1d,$81,$18
	.db $81,$05,$81,$16,$81,$1d,$81,$18,$81
	.db $fd
	.dw .song2ch1loop

; New song
.song2ch2:
.song2ch2loop:
.ref112:
	.db $af
	.db $fd
	.dw .song2ch2loop

; New song
.song2ch3:
.song2ch3loop:
.ref113:
	.db $af
	.db $fd
	.dw .song2ch3loop

; New song
.song2ch4:
.song2ch4loop:
.ref114:
	.db $af
	.db $fd
	.dw .song2ch4loop


; New song
.song3ch0:
	.db $fb,$0b
.song3ch0loop:
.ref115:
	.db $86,$0c,$81,$17,$81,$11,$81,$1c,$81,$10,$81,$1a,$81,$15,$81,$1f
	.db $81
.ref116:
	.db $14,$81,$1f,$81,$19,$81,$24,$81,$18,$81,$22,$81,$11,$81,$1b,$81
.ref117:
	.db $10,$81,$1b,$81,$15,$81,$20,$81,$14,$81,$1e,$81,$0d,$81,$17,$81
	.db $fd
	.dw .song3ch0loop

; New song
.song3ch1:
.song3ch1loop:
.ref118:
	.db $86,$1c,$13,$81,$1c,$21,$18,$81,$21,$1f,$17,$81,$1f,$24,$1c,$81
	.db $24
.ref119:
	.db $24,$1b,$81,$24,$29,$20,$81,$29,$27,$1f,$81,$27,$20,$18,$81,$20
.ref120:
	.db $20,$17,$81,$20,$25,$1c,$81,$25,$23,$1b,$81,$23,$1c,$14,$81,$1c
	.db $fd
	.dw .song3ch1loop

; New song
.song3ch2:
.song3ch2loop:
.ref121:
	.db $82,$23,$26,$28,$2b,$28,$2b,$2d,$30,$2f,$2b,$2a,$26,$28,$24,$23
	.db $1f
.ref122:
	.db $2b,$2e,$30,$33,$30,$33,$35,$38,$37,$33,$32,$2e,$30,$2c,$2b,$27
.ref123:
	.db $27,$2a,$2c,$2f,$2c,$2f,$31,$34,$33,$2f,$2e,$2a,$2c,$28,$27,$23
	.db $fd
	.dw .song3ch2loop

; New song
.song3ch3:
.song3ch3loop:
.ref124:
	.db $9f
.ref125:
	.db $9f
.ref126:
	.db $9f
	.db $fd
	.dw .song3ch3loop

; New song
.song3ch4:
.song3ch4loop:
.ref127:
	.db $9f
.ref128:
	.db $9f
.ref129:
	.db $9f
	.db $fd
	.dw .song3ch4loop


; New song
.song4ch0:
	.db $fb,$06
.ref130:
	.db $fb,$05,$80,$0c,$86,$11,$13,$15,$18,$1d,$1f,$21
.ref131:
	.db $24,$80,$29,$85,$00,$83
.song4ch0loop:
.ref132:
	.db $fb,$06,$80,$24,$81,$1f,$81,$21,$81,$1c,$81,$1f,$81,$18,$81,$1a
	.db $81,$15,$81
.ref133:
	.db $83,$18,$81,$1a,$81,$1f,$85,$24,$85,$21,$81
.ref134:
	.db $83,$1e,$81,$21,$89,$22,$85,$1f,$81
.ref135:
	.db $83,$1c,$81,$1f,$89,$21,$85,$28,$81
	.db $fd
	.dw .song4ch0loop

; New song
.song4ch1:
.ref136:
	.db $80,$13,$15,$18,$1d,$1f,$21,$24,$29
.ref137:
	.db $2b,$2d,$85,$00,$83
.song4ch1loop:
.ref138:
	.db $80,$2b,$81,$24,$81,$26,$81,$21,$81,$24,$81,$1d,$81,$1f,$81,$1a
	.db $81
.ref139:
	.db $83,$1c,$81,$1f,$81,$24,$85,$2b,$85,$2a,$81
.ref140:
	.db $83,$23,$81,$26,$89,$29,$85,$28,$81
.ref141:
	.db $83,$21,$81,$24,$89,$26,$85,$2d,$81
	.db $fd
	.dw .song4ch1loop

; New song
.song4ch2:
.ref142:
	.db $84,$24,$8d
.ref143:
	.db $81,$30,$8b
.song4ch2loop:
.ref144:
	.db $84,$29,$81,$29,$85,$82,$29,$29,$84,$15,$81,$29,$81,$16,$81,$82
	.db $29,$29
.ref145:
	.db $84,$18,$81,$18,$81,$28,$81,$82,$15,$15,$84,$1a,$81,$1a,$81,$28
	.db $81,$82,$1a,$1a
.ref146:
	.db $84,$1f,$81,$1f,$81,$2a,$81,$82,$1f,$1f,$84,$18,$81,$18,$81,$26
	.db $81,$82,$18,$18
.ref147:
	.db $84,$1d,$81,$1d,$81,$1a,$81,$82,$26,$26,$84,$16,$81,$22,$81,$1f
	.db $81,$82,$2b,$2b
	.db $fd
	.dw .song4ch2loop

; New song
.song4ch3:
.ref148:
	.db $8f
.ref149:
	.db $8f
.song4ch3loop:
	.db $ff,$10
	.dw .ref48
	.db $ff,$10
	.dw .ref49
	.db $ff,$10
	.dw .ref49
.ref153:
	.db $01,$81,$0e,$01,$09,$81,$0e,$01,$01,$81,$0e,$01,$09,$81,$09,$01
	.db $fd
	.dw .song4ch3loop

; New song
.song4ch4:
.ref154:
	.db $8f
.ref155:
	.db $8f
.song4ch4loop:
.ref156:
	.db $9f
.ref157:
	.db $9f
.ref158:
	.db $9f
.ref159:
	.db $9f
	.db $fd
	.dw .song4ch4loop
